### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by andisfar** [tonka3000/vscode-qt-tools#32]
[tonka3000.qtvsctools-unresponsive.cpuprofile.txt](https://github.com/tonka3000/vscode-qt-tools/files/5222260/tonka3000.qtvsctools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `qtvsctools`
- Extension Version: `0.6.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\andis\tonka3000.qtvsctools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tonka3000** [comment]
Hey @andisfar ,

can you try out the CPU performance with the webpack branch (#34). The cpu load should now be lower?

Thanks in advance

Tonka

**Comment by andisfar** [comment]
I will give #34 a try when I get the chance

**Comment by andisfar** [comment]
When I build the extension still get a query about the number of files that you are packaging:
"This extension consists of 670 files, out of which 228 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore"

Are you sure that the web pack is working?

**Comment by tonka3000** [comment]
Strange. I have only one js file on my disk and the vsix file now has much lesser files.

How do you build the extension and how do you start it? The package.json looks now at the dist folder instead of the out folder.
Do you use the webpack branch?

**Comment by andisfar** [comment]
I downloaded the commit for #34 and in vscode in the terminal I installed the packages using npm (npm install) then vsce package!
and got the message:

"This extension consists of 670 files, out of which 228 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore"

**Comment by tonka3000** [comment]
Hm, I do the same but my output looks correct. Used git sha1 d945d07d76d0fecb1ca9201170bd53afedd6dd5c

```sh
> npm i
....
vscode-qt-tools> npm run package

> qtvsctools@0.6.0 package C:\sandbox\vscode-qt-tools
> npx vsce package

npx: installed 67 in 5.234s
Executing prepublish script 'npm run vscode:prepublish'...

> qtvsctools@0.6.0 vscode:prepublish C:\sandbox\vscode-qt-tools
> webpack --mode production

Hash: 81f889f419f8824a141c
Version: webpack 4.44.2
Time: 6594ms
Built at: 2020-09-21 14:51:10
           Asset      Size  Chunks                   Chunk Names
    extension.js   428 KiB       0  [emitted]        main
extension.js.map  1.05 MiB       0  [emitted] [dev]  main
Entrypoint main = extension.js extension.js.map
  [0] external "path" 42 bytes {0} [built]
  [1] external "fs" 42 bytes {0} [built]
  [2] external "vscode" 42 bytes {0} [built]
  [3] external "stream" 42 bytes {0} [built]
  [4] external "util" 42 bytes {0} [built]
  [6] external "url" 42 bytes {0} [built]
  [8] external "events" 42 bytes {0} [built]
 [12] external "child_process" 42 bytes {0} [built]
 [13] external "assert" 42 bytes {0} [built]
 [16] external "http" 42 bytes {0} [built]
 [18] external "os" 42 bytes {0} [built]
 [31] external "https" 42 bytes {0} [built]
 [58] external "readline" 42 bytes {0} [built]
[139] external "querystring" 42 bytes {0} [built]
[185] ./src/extension.ts + 6 modules 46.1 KiB {0} [built]
      | ./src/extension.ts 26.3 KiB [built]
      | ./src/tools.ts 1.4 KiB [built]
      | ./src/qt.ts 9.86 KiB [built]
      | ./src/cmake.ts 3.05 KiB [built]
      | ./src/status.ts 835 bytes [built]
      | ./src/downloader.ts 3.38 KiB [built]
      | ./src/logging.ts 1.25 KiB [built]
    + 171 hidden modules

WARNING in ./node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/cacheable-request/src/index.js
 @ ./node_modules/got/index.js
 @ ./node_modules/download/index.js
 @ ./src/downloader.ts
 @ ./src/extension.ts
 DONE  Packaged: C:\sandbox\vscode-qt-tools\qtvsctools-0.6.0.vsix (10 files, 120.07KB)
```

10 files, 120.07KB
