### ISSUE TITLE
Search in documentation

### ISSUE THREAD

**Issue by Shatur95** [tonka3000/vscode-qt-tools#39]
In QtCreator, you can press F1 and get help with the current class. Is it possible to add similar functionality to the command palette to open a web page with the selected class? I would suggest providing a search and if it is empty then the class under the cursor will be found.

**Comment by tonka3000** [comment]
Hey,

In theory that sounds possible. The only problem I had in the past is that I'm not quite sure how to use `assistant` command line args correctly. In need `assistant` to display the help. Getting the text token under your cursor should be possible, but I never done it in vscode.

I tried `-setCurrentFilter` but it never worked for me. Also I'm building qt without it's `.qch` files, so my assistant have only 2 pages of itself in the docs. Do you have some `.qch` files from your Qt installation you can share?

Args:
![image](https://user-images.githubusercontent.com/3163807/99697017-99906880-2a8f-11eb-8a98-90e387d7ef83.png)


Greetings

Tonka

**Comment by Shatur95** [comment]
I suggested to open web page, but your approach is better :)

> Getting the text token under your cursor should be possible, but I never done it in vscode.

I have no experience with extensions, but I know an extension that does exactly [this](https://github.com/Guyutongxue/VSC_CppReference). Perhaps this can be used as a reference.

> Do you have some .qch files from your Qt installation you can share?

Sure. Here is some files. Let me know if you need more.
[Qt-5.15.0.zip](https://github.com/tonka3000/vscode-qt-tools/files/5569488/Qt-5.15.0.zip)

**Comment by tonka3000** [comment]
Thanks for the files.

I already got the word under the cursor position. Now I just have to find out which args are the correct ones from assistant. Maybe I can also add a setting to use the website instead, but I think you get an messagebox everytime which tells you the url before opening.

**Comment by Shatur95** [comment]
>  but I think you get an messagebox everytime which tells you the url before opening.

No, the extension I mentioned above opens the site directly inside VSCode.

**Comment by tonka3000** [comment]
> No, the extension I mentioned above opens the site directly inside VSCode.

Inject via iframe, interesting.

Can you try to call qt assistant from your side with `assistant -setCurrentFilter QWidget`. On my side this do nothing in the assistant (I expect that the search filter will be filled out). Maybe my assistant is broken.

**Comment by Shatur95** [comment]
> Can you try to call qt assistant from your side with assistant -setCurrentFilter QWidget. On my side this do nothing in the assistant (I expect that the search filter will be filled out). Maybe my assistant is broken.

No, unfortunately it just opens Assistant quick guide.

**Comment by tonka3000** [comment]
Then I try the Qt website. When it is a class I can just attach it to the url like https://doc.qt.io/qt-5/qwidget.html. I will checkout the webview/iframe approach, but this can take some time.

**Comment by Shatur95** [comment]
It would be cool, thanks!

**Comment by tonka3000** [comment]
I pushed a first implementation in the #40 PR. You can try it out and tell me what is missing. I just attach the word under the cursor to the website, so it mostly works for classes, functions and methods would not work that way. I'm not sure if there is a json based search integrated in the Qt docs website.

![image](https://user-images.githubusercontent.com/3163807/99729078-af675300-2aba-11eb-9dfa-2cf9232a3a44.png)
