### ISSUE TITLE
Can‘t open *.ui file with "Qt: Edit in Qt Designer" command.

### ISSUE THREAD

**Issue by hierfer** [tonka3000/vscode-qt-tools#60]
Can‘t open *.ui file with "Qt: Edit in Qt Designer" command, but OK with right click and pick "Edit in Qt Designer". When I use the command an error window poped out:
>Command"Qt: Edit in Qt Designer” lead to error (Running the contributed command: 'qttools.currentfileindesigner' failed.)

I've checked the issue#51, seems it is not concerning a cmake problem for it did work in a way. I tried both qt5 and qt6 on my both computers, both got the error.

Is there any difference excuting the same command between typing command and right click pick?

**Comment by tonka3000** [comment]
Hi @hierfer ,

Thanks for your report. I can reproduce the error. It seems that I introduce it with #58 .

> Is there any difference excuting the same command between typing command and right click pick?

Yes. VSCode give different arguments to the command depending on the context.

I will check if I can fix it.

**Comment by tonka3000** [comment]
@hierfer I pushed out 0.10.1 which address your problem.

Thanks for your report 🙏
